import Head from 'next/head';
// import Image from 'next/image';
// import Link from 'next/link';
import { promises as fs } from 'fs';
import path from 'path';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const jsonDirectory = path.join(process.cwd(), 'logs');
  // Read the json data file data.json
  const fileContents = await fs.readFile(
    `${jsonDirectory}/application-2022-11-11.log`,
    'utf8'
  );
  // Return the content of the data file in json format
  return {
    props: {
      fileContents,
    },
  };
}

export default function Home({ fileContents }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>application-2022-11-11 log</h1>
        <pre>{fileContents}</pre>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
