import Head from 'next/head';
// import Image from 'next/image';
// import Link from 'next/link';
import { promises as fs } from 'fs';
import path from 'path';
import styles from '../styles/Home.module.css';

export async function getServerSideProps(context) {
  if (!context.query?.date) {
    return {
      props: {
        fileContents: '...',
        date: 'no ',
      },
    };
  }
  const jsonDirectory = path.join(process.cwd(), 'logs');
  // Read the json data file data.json
  const fileContents = await fs.readFile(
    `${jsonDirectory}/application-${context.query.date}.log`,
    'utf8'
  );
  // Return the content of the data file in json format
  return {
    props: {
      fileContents,
      date: context.query.date,
    },
  };
}

export default function Home({ fileContents, date }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{date} log</h1>
        <pre
          style={{
            whiteSpace: 'pre-wrap',
            padding: 30,
            backgroundColor: '#eee',
            border: '1px solid lightgray',
          }}
        >
          {fileContents}
        </pre>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
